DROP TABLE IF EXISTS TBL_CATEGORIES;
CREATE TABLE TBL_CATEGORIES (
    ID   INTEGER      NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TBL_PRODUCTS;
CREATE TABLE TBL_PRODUCTS (
    ID   INTEGER      NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250) NOT NULL,
    STOCK DECIMAL(10,2) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATE_AT TIMESTAMP NOT NULL,
    CATEGORY_ID   INTEGER      NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES TBL_CATEGORIES(ID)
    
);